/*
 * GENERATED by scripts/gen-studio-schema.js from src/db/schema.js.
 * Do not edit by hand - change the data model, then run `npm run studio:schema`.
 */
export const hiddenTypes = ["session"];

export default [
  {
    "name": "user",
    "title": "Staff user",
    "type": "document",
    "fields": [
      {
        "name": "id",
        "title": "ID",
        "type": "number",
        "readOnly": true,
        "hidden": false
      },
      {
        "name": "email",
        "title": "Email",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "full_name",
        "title": "Full name",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "password_hash",
        "title": "Password hash",
        "readOnly": true,
        "hidden": true,
        "type": "string"
      },
      {
        "name": "role",
        "title": "Role",
        "readOnly": true,
        "type": "string",
        "options": {
          "list": [
            "admin",
            "security",
            "regulator"
          ]
        }
      },
      {
        "name": "status",
        "title": "Status",
        "readOnly": true,
        "type": "string",
        "options": {
          "list": [
            "active",
            "suspended"
          ]
        }
      },
      {
        "name": "failed_attempts",
        "title": "Failed attempts",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "locked_until",
        "title": "Locked until",
        "readOnly": true,
        "type": "datetime"
      },
      {
        "name": "last_login_at",
        "title": "Last login at",
        "readOnly": true,
        "type": "datetime"
      },
      {
        "name": "must_change_pw",
        "title": "Must change pw",
        "readOnly": true,
        "type": "number",
        "options": {
          "list": [
            {
              "title": "No",
              "value": 0
            },
            {
              "title": "Yes",
              "value": 1
            }
          ]
        }
      },
      {
        "name": "avatar",
        "title": "Avatar",
        "readOnly": true,
        "hidden": true,
        "type": "text",
        "rows": 3
      },
      {
        "name": "created_by",
        "title": "Created by",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "created_at",
        "title": "Created at",
        "readOnly": true,
        "type": "datetime"
      },
      {
        "name": "updated_at",
        "title": "Updated at",
        "readOnly": true,
        "type": "datetime"
      }
    ],
    "preview": {
      "select": {
        "title": "full_name",
        "subtitle": "email"
      }
    }
  },
  {
    "name": "session",
    "title": "Session",
    "type": "document",
    "fields": [
      {
        "name": "id",
        "title": "ID",
        "type": "string",
        "readOnly": true,
        "hidden": true
      },
      {
        "name": "user_id",
        "title": "User ID",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "csrf_token",
        "title": "Csrf token",
        "readOnly": true,
        "hidden": true,
        "type": "string"
      },
      {
        "name": "ip",
        "title": "Ip",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "user_agent",
        "title": "User agent",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "created_at",
        "title": "Created at",
        "readOnly": true,
        "type": "datetime"
      },
      {
        "name": "expires_at",
        "title": "Expires at",
        "readOnly": true,
        "type": "datetime"
      },
      {
        "name": "revoked_at",
        "title": "Revoked at",
        "readOnly": true,
        "type": "datetime"
      }
    ],
    "preview": {
      "select": {
        "title": "id",
        "subtitle": "expires_at"
      }
    }
  },
  {
    "name": "product",
    "title": "Product",
    "type": "document",
    "fields": [
      {
        "name": "id",
        "title": "ID",
        "type": "number",
        "readOnly": true,
        "hidden": false
      },
      {
        "name": "sku",
        "title": "Sku",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "name",
        "title": "Name",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "generic_name",
        "title": "Generic name",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "strength",
        "title": "Strength",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "dosage_form",
        "title": "Dosage form",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "pack_size",
        "title": "Pack size",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "manufacturer",
        "title": "Manufacturer",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "category",
        "title": "Category",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "status",
        "title": "Status",
        "readOnly": true,
        "type": "string",
        "options": {
          "list": [
            "active",
            "discontinued"
          ]
        }
      },
      {
        "name": "created_at",
        "title": "Created at",
        "readOnly": true,
        "type": "datetime"
      },
      {
        "name": "updated_at",
        "title": "Updated at",
        "readOnly": true,
        "type": "datetime"
      }
    ],
    "preview": {
      "select": {
        "title": "name",
        "subtitle": "sku"
      }
    }
  },
  {
    "name": "leaflet",
    "title": "Patient leaflet",
    "type": "document",
    "fields": [
      {
        "name": "id",
        "title": "ID",
        "type": "number",
        "readOnly": true,
        "hidden": false
      },
      {
        "name": "product_id",
        "title": "Product ID",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "version",
        "title": "Version",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "language",
        "title": "Language",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "sections",
        "title": "Sections",
        "readOnly": true,
        "type": "array",
        "of": [
          {
            "type": "object",
            "name": "sectionsItem",
            "fields": [
              {
                "name": "heading",
                "title": "Heading",
                "type": "string",
                "readOnly": true
              },
              {
                "name": "body",
                "title": "Body",
                "type": "text",
                "readOnly": true
              }
            ],
            "preview": {
              "select": {
                "title": "heading"
              }
            }
          }
        ]
      },
      {
        "name": "file_id",
        "title": "File ID",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "effective_from",
        "title": "Effective from",
        "readOnly": true,
        "type": "datetime"
      },
      {
        "name": "created_at",
        "title": "Created at",
        "readOnly": true,
        "type": "datetime"
      }
    ],
    "preview": {
      "select": {
        "title": "version",
        "subtitle": "language"
      }
    }
  },
  {
    "name": "batch",
    "title": "Batch",
    "type": "document",
    "fields": [
      {
        "name": "id",
        "title": "ID",
        "type": "number",
        "readOnly": true,
        "hidden": false
      },
      {
        "name": "batch_number",
        "title": "Batch number",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "product_id",
        "title": "Product ID",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "mfg_date",
        "title": "Mfg date",
        "readOnly": true,
        "type": "date"
      },
      {
        "name": "expiry_date",
        "title": "Expiry date",
        "readOnly": true,
        "type": "date"
      },
      {
        "name": "quantity",
        "title": "Quantity",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "serial_width",
        "title": "Serial width",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "status",
        "title": "Status",
        "readOnly": true,
        "type": "string",
        "options": {
          "list": [
            "planned",
            "codes_issued",
            "printed",
            "released",
            "distributed",
            "recalled",
            "closed"
          ]
        }
      },
      {
        "name": "is_test",
        "title": "Is test",
        "readOnly": true,
        "type": "number",
        "options": {
          "list": [
            {
              "title": "No",
              "value": 0
            },
            {
              "title": "Yes",
              "value": 1
            }
          ]
        }
      },
      {
        "name": "leaflet_id",
        "title": "Leaflet ID",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "codes_issued_at",
        "title": "Codes issued at",
        "readOnly": true,
        "type": "datetime"
      },
      {
        "name": "printed_at",
        "title": "Printed at",
        "readOnly": true,
        "type": "datetime"
      },
      {
        "name": "released_at",
        "title": "Released at",
        "readOnly": true,
        "type": "datetime"
      },
      {
        "name": "recalled_at",
        "title": "Recalled at",
        "readOnly": true,
        "type": "datetime"
      },
      {
        "name": "recall_reason",
        "title": "Recall reason",
        "readOnly": true,
        "type": "text",
        "rows": 3
      },
      {
        "name": "notes",
        "title": "Notes",
        "readOnly": true,
        "type": "text",
        "rows": 3
      },
      {
        "name": "created_by",
        "title": "Created by",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "created_at",
        "title": "Created at",
        "readOnly": true,
        "type": "datetime"
      },
      {
        "name": "updated_at",
        "title": "Updated at",
        "readOnly": true,
        "type": "datetime"
      }
    ],
    "preview": {
      "select": {
        "title": "batch_number",
        "subtitle": "status"
      }
    }
  },
  {
    "name": "code",
    "title": "Pack code",
    "type": "document",
    "fields": [
      {
        "name": "id",
        "title": "ID",
        "type": "number",
        "readOnly": true,
        "hidden": false
      },
      {
        "name": "code",
        "title": "Code",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "batch_id",
        "title": "Batch ID",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "product_id",
        "title": "Product ID",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "unit_index",
        "title": "Unit index",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "serial",
        "title": "Serial",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "status",
        "title": "Status",
        "readOnly": true,
        "type": "string",
        "options": {
          "list": [
            "issued",
            "printed",
            "released",
            "verified",
            "flagged",
            "recalled",
            "void"
          ]
        }
      },
      {
        "name": "scan_count",
        "title": "Scan count",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "verified_count",
        "title": "Verified count",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "first_scan_at",
        "title": "First scan at",
        "readOnly": true,
        "type": "datetime"
      },
      {
        "name": "last_scan_at",
        "title": "Last scan at",
        "readOnly": true,
        "type": "datetime"
      },
      {
        "name": "flagged_at",
        "title": "Flagged at",
        "readOnly": true,
        "type": "datetime"
      },
      {
        "name": "created_at",
        "title": "Created at",
        "readOnly": true,
        "type": "datetime"
      }
    ],
    "preview": {
      "select": {
        "title": "code",
        "subtitle": "status"
      }
    }
  },
  {
    "name": "scan",
    "title": "Scan",
    "type": "document",
    "fields": [
      {
        "name": "id",
        "title": "ID",
        "type": "number",
        "readOnly": true,
        "hidden": false
      },
      {
        "name": "code_text",
        "title": "Code text",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "code_id",
        "title": "Code ID",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "batch_id",
        "title": "Batch ID",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "product_id",
        "title": "Product ID",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "verifier_id",
        "title": "Verifier ID",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "result",
        "title": "Result",
        "readOnly": true,
        "type": "string",
        "options": {
          "list": [
            "genuine",
            "flagged",
            "invalid"
          ]
        }
      },
      {
        "name": "reason",
        "title": "Reason",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "channel",
        "title": "Channel",
        "readOnly": true,
        "type": "string",
        "options": {
          "list": [
            "web",
            "sms",
            "api"
          ]
        }
      },
      {
        "name": "signature_state",
        "title": "Signature state",
        "readOnly": true,
        "type": "string",
        "options": {
          "list": [
            "valid",
            "invalid",
            "absent"
          ]
        }
      },
      {
        "name": "scan_number",
        "title": "Scan number",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "ip_hash",
        "title": "Ip hash",
        "readOnly": true,
        "hidden": true,
        "type": "string"
      },
      {
        "name": "msisdn_hash",
        "title": "Msisdn hash",
        "readOnly": true,
        "hidden": true,
        "type": "string"
      },
      {
        "name": "user_agent",
        "title": "User agent",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "country",
        "title": "Country",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "region",
        "title": "Region",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "city",
        "title": "City",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "is_test",
        "title": "Is test",
        "readOnly": true,
        "type": "number",
        "options": {
          "list": [
            {
              "title": "No",
              "value": 0
            },
            {
              "title": "Yes",
              "value": 1
            }
          ]
        }
      },
      {
        "name": "created_at",
        "title": "Created at",
        "readOnly": true,
        "type": "datetime"
      }
    ],
    "preview": {
      "select": {
        "title": "code_text",
        "subtitle": "result"
      }
    }
  },
  {
    "name": "alert",
    "title": "Alert",
    "type": "document",
    "fields": [
      {
        "name": "id",
        "title": "ID",
        "type": "number",
        "readOnly": true,
        "hidden": false
      },
      {
        "name": "type",
        "title": "Type",
        "readOnly": true,
        "type": "string",
        "options": {
          "list": [
            "duplicate_scan",
            "unknown_code",
            "recalled_scan",
            "expired_scan",
            "guess_attack",
            "consumer_report",
            "batch_anomaly"
          ]
        }
      },
      {
        "name": "severity",
        "title": "Severity",
        "readOnly": true,
        "type": "string",
        "options": {
          "list": [
            "low",
            "medium",
            "high",
            "critical"
          ]
        }
      },
      {
        "name": "status",
        "title": "Status",
        "readOnly": true,
        "type": "string",
        "options": {
          "list": [
            "open",
            "investigating",
            "resolved",
            "dismissed"
          ]
        }
      },
      {
        "name": "title",
        "title": "Title",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "detail_json",
        "title": "Detail json",
        "readOnly": true,
        "type": "text",
        "rows": 6
      },
      {
        "name": "ip_hash",
        "title": "Ip hash",
        "readOnly": true,
        "hidden": true,
        "type": "string"
      },
      {
        "name": "code_id",
        "title": "Code ID",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "batch_id",
        "title": "Batch ID",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "scan_id",
        "title": "Scan ID",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "assigned_to",
        "title": "Assigned to",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "resolution_note",
        "title": "Resolution note",
        "readOnly": true,
        "type": "text",
        "rows": 3
      },
      {
        "name": "resolved_by",
        "title": "Resolved by",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "resolved_at",
        "title": "Resolved at",
        "readOnly": true,
        "type": "datetime"
      },
      {
        "name": "created_at",
        "title": "Created at",
        "readOnly": true,
        "type": "datetime"
      },
      {
        "name": "updated_at",
        "title": "Updated at",
        "readOnly": true,
        "type": "datetime"
      }
    ],
    "preview": {
      "select": {
        "title": "title",
        "subtitle": "status"
      }
    }
  },
  {
    "name": "consumerReport",
    "title": "Consumer report",
    "type": "document",
    "fields": [
      {
        "name": "id",
        "title": "ID",
        "type": "number",
        "readOnly": true,
        "hidden": false
      },
      {
        "name": "code_text",
        "title": "Code text",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "code_id",
        "title": "Code ID",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "scan_id",
        "title": "Scan ID",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "alert_id",
        "title": "Alert ID",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "reporter_name",
        "title": "Reporter name",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "reporter_contact",
        "title": "Reporter contact",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "purchase_location",
        "title": "Purchase location",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "description",
        "title": "Description",
        "readOnly": true,
        "type": "text",
        "rows": 3
      },
      {
        "name": "status",
        "title": "Status",
        "readOnly": true,
        "type": "string",
        "options": {
          "list": [
            "new",
            "reviewing",
            "closed"
          ]
        }
      },
      {
        "name": "created_at",
        "title": "Created at",
        "readOnly": true,
        "type": "datetime"
      }
    ],
    "preview": {
      "select": {
        "title": "description",
        "subtitle": "status"
      }
    }
  },
  {
    "name": "shipment",
    "title": "Shipment",
    "type": "document",
    "fields": [
      {
        "name": "id",
        "title": "ID",
        "type": "number",
        "readOnly": true,
        "hidden": false
      },
      {
        "name": "reference",
        "title": "Reference",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "batch_id",
        "title": "Batch ID",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "quantity",
        "title": "Quantity",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "from_site",
        "title": "From site",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "to_name",
        "title": "To name",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "to_type",
        "title": "To type",
        "readOnly": true,
        "type": "string",
        "options": {
          "list": [
            "distributor",
            "pharmacy",
            "hospital"
          ]
        }
      },
      {
        "name": "to_region",
        "title": "To region",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "status",
        "title": "Status",
        "readOnly": true,
        "type": "string",
        "options": {
          "list": [
            "in_transit",
            "received",
            "disputed"
          ]
        }
      },
      {
        "name": "shipped_at",
        "title": "Shipped at",
        "readOnly": true,
        "type": "datetime"
      },
      {
        "name": "received_at",
        "title": "Received at",
        "readOnly": true,
        "type": "datetime"
      },
      {
        "name": "created_at",
        "title": "Created at",
        "readOnly": true,
        "type": "datetime"
      }
    ],
    "preview": {
      "select": {
        "title": "reference",
        "subtitle": "to_name"
      }
    }
  },
  {
    "name": "auditLog",
    "title": "Audit entry",
    "type": "document",
    "fields": [
      {
        "name": "id",
        "title": "ID",
        "type": "number",
        "readOnly": true,
        "hidden": false
      },
      {
        "name": "actor_id",
        "title": "Actor ID",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "actor_email",
        "title": "Actor email",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "action",
        "title": "Action",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "entity_type",
        "title": "Entity type",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "entity_id",
        "title": "Entity ID",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "detail_json",
        "title": "Detail json",
        "readOnly": true,
        "type": "text",
        "rows": 6
      },
      {
        "name": "ip",
        "title": "Ip",
        "readOnly": true,
        "hidden": true,
        "type": "string"
      },
      {
        "name": "user_agent",
        "title": "User agent",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "created_at",
        "title": "Created at",
        "readOnly": true,
        "type": "datetime"
      }
    ],
    "preview": {
      "select": {
        "title": "action",
        "subtitle": "actor_email"
      }
    }
  },
  {
    "name": "smsLog",
    "title": "SMS message",
    "type": "document",
    "fields": [
      {
        "name": "id",
        "title": "ID",
        "type": "number",
        "readOnly": true,
        "hidden": false
      },
      {
        "name": "direction",
        "title": "Direction",
        "readOnly": true,
        "type": "string",
        "options": {
          "list": [
            "inbound",
            "outbound"
          ]
        }
      },
      {
        "name": "msisdn_hash",
        "title": "Msisdn hash",
        "readOnly": true,
        "hidden": true,
        "type": "string"
      },
      {
        "name": "body",
        "title": "Body",
        "readOnly": true,
        "type": "text",
        "rows": 3
      },
      {
        "name": "scan_id",
        "title": "Scan ID",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "provider",
        "title": "Provider",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "status",
        "title": "Status",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "created_at",
        "title": "Created at",
        "readOnly": true,
        "type": "datetime"
      }
    ],
    "preview": {
      "select": {
        "title": "direction",
        "subtitle": "created_at"
      }
    }
  },
  {
    "name": "setting",
    "title": "Setting",
    "type": "document",
    "fields": [
      {
        "name": "id",
        "title": "ID",
        "type": "string",
        "readOnly": true,
        "hidden": false
      },
      {
        "name": "key",
        "title": "Key",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "value",
        "title": "Value",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "description",
        "title": "Description",
        "readOnly": true,
        "type": "text",
        "rows": 3
      },
      {
        "name": "updated_by",
        "title": "Updated by",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "updated_at",
        "title": "Updated at",
        "readOnly": true,
        "type": "datetime"
      }
    ],
    "preview": {
      "select": {
        "title": "key",
        "subtitle": "value"
      }
    }
  },
  {
    "name": "verifier",
    "title": "Customer",
    "type": "document",
    "fields": [
      {
        "name": "id",
        "title": "ID",
        "type": "number",
        "readOnly": true,
        "hidden": false
      },
      {
        "name": "token_hash",
        "title": "Token hash",
        "readOnly": true,
        "hidden": true,
        "type": "string"
      },
      {
        "name": "full_name",
        "title": "Full name",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "phone",
        "title": "Phone",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "email",
        "title": "Email",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "role",
        "title": "Role",
        "readOnly": true,
        "type": "string",
        "options": {
          "list": [
            "patient",
            "caregiver",
            "pharmacist",
            "health_worker",
            "retailer",
            "other"
          ]
        }
      },
      {
        "name": "city",
        "title": "City",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "purchase_location",
        "title": "Purchase location",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "consent_at",
        "title": "Consent at",
        "readOnly": true,
        "type": "datetime"
      },
      {
        "name": "policy_version",
        "title": "Policy version",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "ip_hash",
        "title": "Ip hash",
        "readOnly": true,
        "hidden": true,
        "type": "string"
      },
      {
        "name": "user_agent",
        "title": "User agent",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "check_count",
        "title": "Check count",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "last_check_at",
        "title": "Last check at",
        "readOnly": true,
        "type": "datetime"
      },
      {
        "name": "created_at",
        "title": "Created at",
        "readOnly": true,
        "type": "datetime"
      }
    ],
    "preview": {
      "select": {
        "title": "full_name",
        "subtitle": "phone"
      }
    }
  },
  {
    "name": "leafletFile",
    "title": "Leaflet PDF",
    "type": "document",
    "fields": [
      {
        "name": "id",
        "title": "ID",
        "type": "number",
        "readOnly": true,
        "hidden": false
      },
      {
        "name": "filename",
        "title": "Filename",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "size",
        "title": "Size",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "sha256",
        "title": "Sha256",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "status",
        "title": "Status",
        "readOnly": true,
        "type": "string",
        "options": {
          "list": [
            "pending",
            "ready"
          ]
        }
      },
      {
        "name": "received",
        "title": "Received",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "chunks",
        "title": "Chunks",
        "readOnly": true,
        "type": "number"
      },
      {
        "name": "pieces",
        "title": "Pieces",
        "readOnly": true,
        "type": "array",
        "of": [
          {
            "type": "object",
            "name": "piecesItem",
            "fields": [
              {
                "name": "asset_id",
                "title": "Asset ID",
                "type": "string",
                "readOnly": true
              },
              {
                "name": "url",
                "title": "Url",
                "type": "string",
                "readOnly": true
              },
              {
                "name": "size",
                "title": "Size",
                "type": "number",
                "readOnly": true
              },
              {
                "name": "sha256",
                "title": "Sha256",
                "type": "string",
                "readOnly": true
              }
            ],
            "preview": {
              "select": {
                "title": "asset_id"
              }
            }
          }
        ]
      },
      {
        "name": "created_at",
        "title": "Created at",
        "readOnly": true,
        "type": "datetime"
      }
    ],
    "preview": {
      "select": {
        "title": "filename",
        "subtitle": "status"
      }
    }
  }
];
