#!/usr/bin/env node
/**
 * First-run setup.
 *
 *   npm run setup
 *
 * Creates a .env with freshly generated secrets (never overwriting an existing
 * one), applies the schema, and loads the demonstration data.
 *
 * The generated CODE_SECRET is the important one: it signs the checksum of
 * every code this installation will ever mint. Rotating it later invalidates
 * every code already printed on a physical pack, so the file it lands in
 * should be treated as a permanent, backed-up secret.
 */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(fileURLToPath(new URL('..', import.meta.url)));
const ENV_PATH = path.join(ROOT, '.env');

const secret = () => crypto.randomBytes(48).toString('base64url');

/*
 * The .env template lives here rather than in a checked-in .env.example, so a
 * fresh clone needs nothing but this script to come up. Every key below is
 * read in src/config.js, which is the authoritative list and documents what
 * each one does - add a key there first, then here.
 *
 * The three secrets are filled in at write time, never shipped with a value.
 */
const TEMPLATE = (s) => `# QR Shield - generated by \`npm run setup\`. Never commit this file.

NODE_ENV=development
PORT=3000

# Baked into printed QR codes. MUST be the real HTTPS origin in production:
# once a code is printed on a pack, this URL cannot be changed.
PUBLIC_BASE_URL=http://localhost:3000

# --- Secrets ---------------------------------------------------------------
# SESSION_SECRET  signs admin session tokens (rotating it logs everyone out).
# CODE_SECRET     signs the QR payload of every serialized code.
#                 *** ROTATING CODE_SECRET INVALIDATES THE SIGNATURE OF EVERY
#                 CODE ALREADY PRINTED ON PHYSICAL PACKS. Treat as permanent. ***
SESSION_SECRET=${s()}
CODE_SECRET=${s()}

# --- Database: Sanity ------------------------------------------------------
# All data lives in a Sanity dataset. These are read by the server only and
# are never sent to the browser. Keep the dataset PRIVATE.
#   SANITY_API_TOKEN: sanity.io/manage -> your project -> API -> Tokens ->
#   Add API token, with Editor permissions. Treat it like a password.
# Leave any of them empty to run on the local file below instead.
SANITY_PROJECT_ID=
SANITY_DATASET=production
SANITY_API_TOKEN=

# Local fallback store, used when Sanity is not configured.
DB_FILE=./data/qrshield.json

# --- Sessions --------------------------------------------------------------
SESSION_TTL_HOURS=8
# Send session cookies only over HTTPS. Leave false for local http dev.
COOKIE_SECURE=false

# --- Rate limiting (per client IP) -----------------------------------------
RL_VERIFY_PER_MIN=12
RL_VERIFY_PER_HOUR=80
RL_LOGIN_PER_15MIN=5
RL_REPORT_PER_HOUR=5
# Consecutive unknown-code lookups from one IP before a guessing alert fires.
GUESS_ALERT_THRESHOLD=8

# --- Account lockout -------------------------------------------------------
LOGIN_MAX_FAILURES=5
LOGIN_LOCKOUT_MINUTES=15

# --- SMS fallback ----------------------------------------------------------
# console = log outbound texts to stdout (development default)
# twilio  = real Twilio REST API (fill in the credentials below)
SMS_PROVIDER=console
SMS_FROM=QRSHIELD
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
# Shared secret required on POST /api/sms/inbound so only your gateway can post.
SMS_WEBHOOK_SECRET=${s()}

# --- Seed admin (used by \`npm run db:seed\` only) ---------------------------
SEED_ADMIN_EMAIL=admin@qrshield.example
SEED_ADMIN_PASSWORD=ChangeMe!2026
`;

console.log('\nQR Shield setup\n' + '='.repeat(52));

if (fs.existsSync(ENV_PATH)) {
  console.log('\n.env already exists - leaving it untouched.');
  console.log('Delete it first if you want fresh secrets generated.');
} else {
  fs.writeFileSync(ENV_PATH, TEMPLATE(secret), { mode: 0o600 });
  console.log('\nCreated .env with freshly generated secrets.');
  console.log('  SESSION_SECRET     rotating this signs everyone out');
  console.log('  CODE_SECRET        treat as PERMANENT once codes are printed');
  console.log('  SMS_WEBHOOK_SECRET give this to your SMS gateway');
}

console.log('\nLoading the demo data...\n');
const result = spawnSync(process.execPath, [path.join(ROOT, 'scripts', 'seed.js')], {
  stdio: 'inherit',
  cwd: ROOT,
});

if (result.status !== 0) {
  console.error('\nSetup failed while seeding.');
  process.exit(result.status ?? 1);
}

console.log('='.repeat(52));
console.log('Setup complete. Start the server with:\n');
console.log('  npm start\n');
